title: XuTsing
description: My Personal Blog
author: Xu Tsing
logo: https://tsingxu430.github.io/TsingXu/static/img/avatar.png
github: https://github.com/tsingxu430
about: Web Front developer
disqus_shortname: about tsing
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Photos
      url: /photos/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/tsingxu430
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      
social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "https://tsingxu430.github.io/TsingXu"
baseurl: "/TsingXu"
paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
